# Generated by Django 3.0.7 on 2020-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pix',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state_of_origin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pix',
            field=models.ImageField(default='profile_pix/default.png', upload_to='profile_pix'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
