# Generated by Django 3.0.7 on 2020-07-15 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caviet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliders', models.ImageField(upload_to='image/slides')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('preview', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField(max_length=20)),
                ('task_description', models.CharField(max_length=150)),
                ('task_date', models.DateField(blank=True, default=datetime.date.today)),
                ('time_assigned', models.TimeField(auto_now=True)),
                ('time_completed', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='unicornabout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='image/about')),
                ('about', models.TextField(max_length=200)),
                ('history', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='unicornService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(max_length=200)),
                ('clients_remark', models.TextField(default=True, max_length=80)),
            ],
        ),
    ]
