# Generated by Django 3.0.7 on 2020-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unicornservice',
            name='services',
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='business_development',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='software_development',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='software_security',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='tech_consultancy',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
