# Generated by Django 3.0.7 on 2020-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0002_auto_20200716_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicornservice',
            name='software_development',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
