# Generated by Django 3.0.7 on 2020-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0003_auto_20200717_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='unicornservice',
            name='description',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
