# Generated by Django 3.0.7 on 2020-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0004_unicornservice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portflio_file', models.ImageField(upload_to='images/portfolio')),
                ('product_description', models.CharField(max_length=80)),
                ('product_price', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='data_visualization',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
