# Generated by Django 3.0.7 on 2020-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0005_auto_20200724_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productportfolio',
            name='product_description',
            field=models.CharField(help_text='Add your product description here..', max_length=80),
        ),
    ]
