# Generated by Django 3.0.7 on 2020-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0006_auto_20200724_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='productportfolio',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
