# Generated by Django 3.0.7 on 2020-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0007_productportfolio_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productportfolio',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
