# Generated by Django 3.0.7 on 2020-07-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0008_auto_20200724_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productportfolio',
            name='date_created',
        ),
    ]
