# Generated by Django 3.0.7 on 2020-07-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0009_remove_productportfolio_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productportfolio',
            old_name='portflio_file',
            new_name='portfolio_file',
        ),
    ]
