# Generated by Django 3.0.7 on 2020-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0010_auto_20200724_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='productportfolio',
            name='date_created',
            field=models.DateTimeField(default=None),
        ),
    ]
