# Generated by Django 3.0.7 on 2020-07-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0011_productportfolio_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.PositiveSmallIntegerField(help_text='Make integer rating here')),
                ('review_text', models.TextField(help_text='Write a review here...', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='productportfolio',
            name='portfolio_file',
            field=models.ImageField(help_text='Add a photo of your portfolio here', upload_to='images/portfolio'),
        ),
    ]
