# Generated by Django 3.0.7 on 2020-07-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0012_auto_20200726_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unicornservice',
            name='business_development',
        ),
        migrations.RemoveField(
            model_name='unicornservice',
            name='clients_remark',
        ),
    ]
