# Generated by Django 3.0.7 on 2020-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0013_auto_20200726_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Indicate your fullname', max_length=30)),
                ('mobile', models.PositiveSmallIntegerField(help_text='Please indicate your mobile number')),
                ('businessname', models.CharField(help_text='Write your business name', max_length=20)),
                ('business_category', models.CharField(choices=[('Corporation', 'Corporation'), ('Medium Enterprise', 'Medium Enterprise'), ('Small Enterprise', 'Small Enterprise'), ('Micro Enterprise', 'Micro Enterprise')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='productportfolio',
            name='date_created',
            field=models.DateTimeField(default=None, help_text='Add date of Software creation'),
        ),
        migrations.AlterField(
            model_name='productportfolio',
            name='product_price',
            field=models.IntegerField(help_text='Add a valid price here'),
        ),
        migrations.AlterField(
            model_name='unicornservice',
            name='description',
            field=models.TextField(default=None, help_text='Write your service description here', max_length=150),
        ),
    ]
