# Generated by Django 3.0.7 on 2020-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0014_auto_20200727_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='productportfolio',
            name='product_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
