# Generated by Django 3.0.7 on 2020-08-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pekuric_mgt', '0015_productportfolio_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productportfolio',
            name='product_name',
            field=models.CharField(default=None, help_text='Add a product name here', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField(default=0)),
                ('review_note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pekuric_mgt.ProductPortfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
