# Generated by Django 3.0.7 on 2020-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0016_auto_20200805_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
