# Generated by Django 3.0.7 on 2020-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0017_customerinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productportfolio',
            name='product_name',
            field=models.CharField(default=None, help_text='Add a product name here', max_length=50),
        ),
    ]
