# Generated by Django 3.0.7 on 2020-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0018_auto_20200808_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unicornservice',
            options={'verbose_name': ['Services']},
        ),
        migrations.RenameField(
            model_name='unicornservice',
            old_name='description',
            new_name='service_description',
        ),
        migrations.RemoveField(
            model_name='unicornservice',
            name='data_visualization',
        ),
        migrations.RemoveField(
            model_name='unicornservice',
            name='software_development',
        ),
        migrations.RemoveField(
            model_name='unicornservice',
            name='software_security',
        ),
        migrations.RemoveField(
            model_name='unicornservice',
            name='tech_consultancy',
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='service_icon',
            field=models.ImageField(default=None, upload_to='image/services'),
        ),
        migrations.AddField(
            model_name='unicornservice',
            name='service_title',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Software Security', 'Software Security'), ('Data Science', 'Data Visualization'), ('Software Training', 'Software Training'), ('Business Consultancy', 'Business Consultancy')], default=None, help_text='Add Service Title', max_length=40),
        ),
    ]
