# Generated by Django 3.0.7 on 2020-08-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0021_auto_20200810_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicornservice',
            name='service_title',
            field=models.CharField(choices=[('', 'Choose'), ('Software Development', 'Software Development'), ('Software Security', 'Software Security'), ('Data Science', 'Data Visualization'), ('Software Training', 'Software Training'), ('Business Consultancy', 'Business Consultancy')], default=None, help_text='Add Service Title', max_length=40),
        ),
    ]
