# Generated by Django 3.0.7 on 2020-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0024_auto_20200810_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicornservice',
            name='service_icon',
            field=models.FileField(upload_to='images/services/%Y/%m/'),
        ),
    ]
