# Generated by Django 3.0.7 on 2020-08-13 14:27

from django.db import migrations, models
import pekuric_mgt.validator


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0025_auto_20200810_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicornservice',
            name='service_icon',
            field=models.FileField(upload_to='images/services/%Y/%m/', validators=[pekuric_mgt.validator.ExtensionValidator]),
        ),
    ]
