# Generated by Django 3.0.7 on 2020-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0026_auto_20200813_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurhaseForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
