# Generated by Django 3.0.7 on 2020-08-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0027_auto_20200814_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerPurhaseForm',
            new_name='CustomerPurchaseForm',
        ),
    ]
