# Generated by Django 3.0.7 on 2020-08-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pekuric_mgt', '0028_auto_20200814_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unicornservice',
            name='service_icon',
            field=models.FileField(upload_to='images/services/%Y/%m/'),
        ),
    ]
