# Generated by Django 3.0.7 on 2020-08-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.TextField(max_length=30)),
                ('course_logo', models.ImageField(upload_to='courses/images/')),
                ('course_description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['course_title'],
            },
        ),
    ]
